/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as InboxIdRouteImport } from './routes/inbox.$id'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardMailboxesRouteImport } from './routes/dashboard.mailboxes'
import { Route as DashboardEmailsRouteImport } from './routes/dashboard.emails'
import { Route as DashboardDomainsRouteImport } from './routes/dashboard.domains'
import { Route as DashboardCreateRouteImport } from './routes/dashboard.create'
import { Route as DashboardApiUsageRouteImport } from './routes/dashboard.api-usage'
import { Route as DashboardApiKeysRouteImport } from './routes/dashboard.api-keys'
import { Route as DashboardMailboxesIdRouteImport } from './routes/dashboard.mailboxes.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const InboxIdRoute = InboxIdRouteImport.update({
  id: '/inbox/$id',
  path: '/inbox/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMailboxesRoute = DashboardMailboxesRouteImport.update({
  id: '/mailboxes',
  path: '/mailboxes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEmailsRoute = DashboardEmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDomainsRoute = DashboardDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCreateRoute = DashboardCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardApiUsageRoute = DashboardApiUsageRouteImport.update({
  id: '/api-usage',
  path: '/api-usage',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardApiKeysRoute = DashboardApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMailboxesIdRoute = DashboardMailboxesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardMailboxesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/api-keys': typeof DashboardApiKeysRoute
  '/dashboard/api-usage': typeof DashboardApiUsageRoute
  '/dashboard/create': typeof DashboardCreateRoute
  '/dashboard/domains': typeof DashboardDomainsRoute
  '/dashboard/emails': typeof DashboardEmailsRoute
  '/dashboard/mailboxes': typeof DashboardMailboxesRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/inbox/$id': typeof InboxIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/mailboxes/$id': typeof DashboardMailboxesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/api-keys': typeof DashboardApiKeysRoute
  '/dashboard/api-usage': typeof DashboardApiUsageRoute
  '/dashboard/create': typeof DashboardCreateRoute
  '/dashboard/domains': typeof DashboardDomainsRoute
  '/dashboard/emails': typeof DashboardEmailsRoute
  '/dashboard/mailboxes': typeof DashboardMailboxesRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/inbox/$id': typeof InboxIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/mailboxes/$id': typeof DashboardMailboxesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/api-keys': typeof DashboardApiKeysRoute
  '/dashboard/api-usage': typeof DashboardApiUsageRoute
  '/dashboard/create': typeof DashboardCreateRoute
  '/dashboard/domains': typeof DashboardDomainsRoute
  '/dashboard/emails': typeof DashboardEmailsRoute
  '/dashboard/mailboxes': typeof DashboardMailboxesRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/inbox/$id': typeof InboxIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/mailboxes/$id': typeof DashboardMailboxesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/dashboard/api-keys'
    | '/dashboard/api-usage'
    | '/dashboard/create'
    | '/dashboard/domains'
    | '/dashboard/emails'
    | '/dashboard/mailboxes'
    | '/dashboard/settings'
    | '/inbox/$id'
    | '/dashboard/'
    | '/dashboard/mailboxes/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/dashboard/api-keys'
    | '/dashboard/api-usage'
    | '/dashboard/create'
    | '/dashboard/domains'
    | '/dashboard/emails'
    | '/dashboard/mailboxes'
    | '/dashboard/settings'
    | '/inbox/$id'
    | '/dashboard'
    | '/dashboard/mailboxes/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/dashboard/api-keys'
    | '/dashboard/api-usage'
    | '/dashboard/create'
    | '/dashboard/domains'
    | '/dashboard/emails'
    | '/dashboard/mailboxes'
    | '/dashboard/settings'
    | '/inbox/$id'
    | '/dashboard/'
    | '/dashboard/mailboxes/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  InboxIdRoute: typeof InboxIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/inbox/$id': {
      id: '/inbox/$id'
      path: '/inbox/$id'
      fullPath: '/inbox/$id'
      preLoaderRoute: typeof InboxIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/mailboxes': {
      id: '/dashboard/mailboxes'
      path: '/mailboxes'
      fullPath: '/dashboard/mailboxes'
      preLoaderRoute: typeof DashboardMailboxesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/emails': {
      id: '/dashboard/emails'
      path: '/emails'
      fullPath: '/dashboard/emails'
      preLoaderRoute: typeof DashboardEmailsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/domains': {
      id: '/dashboard/domains'
      path: '/domains'
      fullPath: '/dashboard/domains'
      preLoaderRoute: typeof DashboardDomainsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/create': {
      id: '/dashboard/create'
      path: '/create'
      fullPath: '/dashboard/create'
      preLoaderRoute: typeof DashboardCreateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/api-usage': {
      id: '/dashboard/api-usage'
      path: '/api-usage'
      fullPath: '/dashboard/api-usage'
      preLoaderRoute: typeof DashboardApiUsageRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/api-keys': {
      id: '/dashboard/api-keys'
      path: '/api-keys'
      fullPath: '/dashboard/api-keys'
      preLoaderRoute: typeof DashboardApiKeysRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/mailboxes/$id': {
      id: '/dashboard/mailboxes/$id'
      path: '/$id'
      fullPath: '/dashboard/mailboxes/$id'
      preLoaderRoute: typeof DashboardMailboxesIdRouteImport
      parentRoute: typeof DashboardMailboxesRoute
    }
  }
}

interface DashboardMailboxesRouteChildren {
  DashboardMailboxesIdRoute: typeof DashboardMailboxesIdRoute
}

const DashboardMailboxesRouteChildren: DashboardMailboxesRouteChildren = {
  DashboardMailboxesIdRoute: DashboardMailboxesIdRoute,
}

const DashboardMailboxesRouteWithChildren =
  DashboardMailboxesRoute._addFileChildren(DashboardMailboxesRouteChildren)

interface DashboardRouteChildren {
  DashboardApiKeysRoute: typeof DashboardApiKeysRoute
  DashboardApiUsageRoute: typeof DashboardApiUsageRoute
  DashboardCreateRoute: typeof DashboardCreateRoute
  DashboardDomainsRoute: typeof DashboardDomainsRoute
  DashboardEmailsRoute: typeof DashboardEmailsRoute
  DashboardMailboxesRoute: typeof DashboardMailboxesRouteWithChildren
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardApiKeysRoute: DashboardApiKeysRoute,
  DashboardApiUsageRoute: DashboardApiUsageRoute,
  DashboardCreateRoute: DashboardCreateRoute,
  DashboardDomainsRoute: DashboardDomainsRoute,
  DashboardEmailsRoute: DashboardEmailsRoute,
  DashboardMailboxesRoute: DashboardMailboxesRouteWithChildren,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  InboxIdRoute: InboxIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
